package galacticwars.clonewars.progression;

public enum ProgressionEventType {
    CAMPAIGN_RECHECK,
    FACTION_PLEDGED,
    CREDIT_TRANSACTION,
    RECRUIT_HIRED,
    PROFESSION_ASSIGNED,
    DELIVERY_COMPLETED,
    BUILDING_COMPLETED,
    PLANET_VISITED,
    VEHICLE_ACQUIRED,
    FORCE_ABILITY_UNLOCKED,
    QUEST_ADVANCED,
    TRADE_COMPLETED,
    REGION_CAPTURED
}
